# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace '../XonSNN'

target 'XonSNNDashboard' do
  platform :ios, '13.2'
  
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XonSNNDashboard
  
  
  # pod 'SwiftCharts', '~> 0.6.5'
  pod 'Charts'
  

  target 'XonSNNDashboardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XonSNNDashboardUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
